### ISSUE TITLE
Prescription MM1-1_DO1 not found in the Biomass Succession Harvest Effects Table

### ISSUE THREAD

**Issue by gsotnik** [LANDIS-II-Foundation/Extension-Biomass-Succession#35]
Prescription names with wildcards ('*') appear to not work.

   HarvestReductionParameters
>> Name           Wood   Leaf  Cohort Cohort
>> Reduct         Reduct Wood  Remove LeafRemove
   MM*               0.5        0.15     0.8         0.0

[Landis-log.txt](https://github.com/LANDIS-II-Foundation/Extension-Biomass-Succession/files/5961523/Landis-log.txt)

**Comment by rmscheller** [comment]
Garry,

I only tested it against Biomass Succession.  Is SOSIEL sharing a SiteVar "Harvest.PrescriptionName"?

Looking here, it seems not:  https://github.com/LANDIS-II-Foundation/Extension-SOSIEL-Harvest/blob/master/src/SiteVars.cs

L30 is commented out and so that variable is not being shared.  Also, L31, all are set to 'SOSIEL' and so that is the PrescriptionName unless overwritten elsewhere in the code.
