### ISSUE TITLE
Needs CohortPartialMortality to use the new Library.BiomassCohorts-v2

### ISSUE THREAD

**Issue by rmscheller** [LANDIS-II-Foundation/Extension-Biomass-Succession#9]

**Comment by rmscheller** [comment]
Austen, I updated to fix a few little bugs and to clean up the build.  I successfully removed the package.config business, which gets rid of outdated dependencies.  However, it still needs basic testing.

**Comment by bmarron18** [comment]
Is the basic testing to check the fix for the exception:

Loading Biomass Harvest extension ...
  Registering Data:  Harvest.PrescriptionName.
  Registering Data:  Harvest.TimeOfLastEvent.
  Registering Data:  Harvest.CohortsDamaged.
The data type of site variable "Succession.BiomassCohorts" is Landis.Library.BiomassCohorts.ISiteCohorts, not Landis.Library.BiomassCohorts.ISiteCohorts

If so, can run it.

**Comment by rmscheller** [comment]
Bruce, 
That is a good place to start.  The next test after that will be the same you did for NECN: Is partial harvesting changing the amount of dead woody material?

**Comment by bmarron18** [comment]
Passed QAQC; close issue.
